axis_linear:                # Right analog
  x: 4
  y: 3
scale_linear:
  x: 1.5
  y: -1.5
axis_angular:               # Left analog
  yaw: 0
scale_angular:
  yaw: 0.5
enable_button: 6            # L2
enable_turbo_button: 7      # R2
